import { useState } from 'react';
import { router, useForm, usePage } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { Button } from '@/Components/UI/button';
import { Input } from '@/Components/UI/input';
import { Label } from '@/Components/UI/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/Components/UI/card';
import type { SharedPageProps } from '@/types/index.d';

interface InviteCodeItem {
  id: string;
  code: string;
  is_used: boolean;
  expires_at: string;
  created_at: string;
  generator?: { name: string };
  used_by_user?: { name: string };
}

interface PaginatedCodes {
  data: InviteCodeItem[];
  current_page: number;
  last_page: number;
  total: number;
}

interface InviteCodesIndexProps extends SharedPageProps {
  codes: PaginatedCodes;
  filters: {
    search?: string;
    status?: string;
  };
}

export default function AdminInviteCodesIndex() {
  const { codes, filters } = usePage<InviteCodesIndexProps>().props;

  const [search, setSearch] = useState(filters.search || '');
  const [selectedStatus, setSelectedStatus] = useState(filters.status || '');
  const [showGenerateModal, setShowGenerateModal] = useState(false);

  const { data, setData, post, processing, reset } = useForm({
    count: 5,
    expiry_days: 30,
  });

  const handleFilter = (e: React.FormEvent) => {
    e.preventDefault();
    router.get('/admin/invite-codes', {
      search,
      status: selectedStatus,
    }, { preserveState: true });
  };

  const handleGenerateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    post('/admin/invite-codes', {
      onSuccess: () => {
        setShowGenerateModal(false);
        reset();
      },
    });
  };

  const handleDelete = (id: string) => {
    if (confirm('Delete this invite code?')) {
      router.delete(`/admin/invite-codes/${id}`);
    }
  };

  return (
    <AdminLayout title="Invite Codes">
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-foreground">Invite Codes Management</h1>
            <p className="text-sm text-muted-foreground">
              Total {codes.total} invite codes in system.
            </p>
          </div>
          <Button onClick={() => setShowGenerateModal(true)}>
            + Generate Invite Codes
          </Button>
        </div>

        {/* Filters */}
        <Card className="p-4">
          <form onSubmit={handleFilter} className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <Input
              placeholder="Search code..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />

            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            >
              <option value="">All Statuses</option>
              <option value="valid">Valid / Unused Only</option>
              <option value="used">Used Only</option>
              <option value="expired">Expired Only</option>
            </select>

            <Button type="submit">Filter</Button>
          </form>
        </Card>

        {/* Invite Codes Table */}
        <Card className="overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="border-b border-border bg-muted/50 text-xs font-semibold uppercase text-muted-foreground">
                <tr>
                  <th className="p-4">Invite Code</th>
                  <th className="p-4">Status</th>
                  <th className="p-4">Generated By</th>
                  <th className="p-4">Used By</th>
                  <th className="p-4">Expires</th>
                  <th className="p-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {codes.data.map((code) => {
                  const isExpired = new Date(code.expires_at) <= new Date();

                  return (
                    <tr key={code.id} className="hover:bg-muted/30 transition-colors">
                      <td className="p-4">
                        <span className="font-mono text-sm font-bold tracking-wider text-primary bg-primary/10 px-2 py-1 rounded">
                          {code.code}
                        </span>
                      </td>
                      <td className="p-4">
                        {code.is_used ? (
                          <span className="px-2 py-0.5 text-xs rounded bg-muted text-muted-foreground font-medium">Used</span>
                        ) : isExpired ? (
                          <span className="px-2 py-0.5 text-xs rounded bg-destructive/10 text-destructive font-medium">Expired</span>
                        ) : (
                          <span className="px-2 py-0.5 text-xs rounded bg-emerald-500/10 text-emerald-500 font-medium">Valid</span>
                        )}
                      </td>
                      <td className="p-4 text-xs text-muted-foreground">
                        {code.generator?.name ?? 'Admin'}
                      </td>
                      <td className="p-4 text-xs text-muted-foreground">
                        {code.used_by_user?.name ?? '-'}
                      </td>
                      <td className="p-4 text-xs text-muted-foreground">
                        {new Date(code.expires_at).toLocaleDateString()}
                      </td>
                      <td className="p-4 text-right">
                        <button
                          type="button"
                          onClick={() => handleDelete(code.id)}
                          className="px-2 py-1 text-xs text-destructive hover:bg-destructive/10 rounded"
                        >
                          Delete
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          {codes.last_page > 1 && (
            <div className="p-4 border-t border-border flex items-center justify-between">
              <span className="text-xs text-muted-foreground">
                Page {codes.current_page} of {codes.last_page}
              </span>
              <div className="flex gap-2">
                {codes.current_page > 1 && (
                  <button
                    type="button"
                    onClick={() => router.get(`/admin/invite-codes?page=${codes.current_page - 1}`)}
                    className="px-3 py-1 text-xs rounded border border-border hover:bg-accent"
                  >
                    Previous
                  </button>
                )}
                {codes.current_page < codes.last_page && (
                  <button
                    type="button"
                    onClick={() => router.get(`/admin/invite-codes?page=${codes.current_page + 1}`)}
                    className="px-3 py-1 text-xs rounded border border-border hover:bg-accent"
                  >
                    Next
                  </button>
                )}
              </div>
            </div>
          )}
        </Card>

        {/* Generate Invite Code Modal */}
        {showGenerateModal && (
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <Card className="max-w-md w-full">
              <CardHeader>
                <CardTitle className="text-lg">Generate Batch Invite Codes</CardTitle>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleGenerateSubmit} className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="count">Quantity to Generate</Label>
                    <Input
                      id="count"
                      type="number"
                      min={1}
                      max={50}
                      value={data.count}
                      onChange={(e) => setData('count', parseInt(e.target.value) || 1)}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="expiry_days">Validity Duration (Days)</Label>
                    <Input
                      id="expiry_days"
                      type="number"
                      min={1}
                      max={90}
                      value={data.expiry_days}
                      onChange={(e) => setData('expiry_days', parseInt(e.target.value) || 30)}
                      required
                    />
                  </div>

                  <div className="flex justify-end gap-2 pt-4 border-t border-border">
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => setShowGenerateModal(false)}
                    >
                      Cancel
                    </Button>
                    <Button type="submit" disabled={processing}>
                      Generate Codes
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </AdminLayout>
  );
}
